### Request 3
POST http://127.0.0.1:8000/api/auth/register/
Content-Type: application/json
Accept: application/json

{
    "username": "root3",
    "email": "root@blog.com",
    "password": "123456789"
}

### Request 3
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json
Accept: application/json

{
    "username": "root3",
    "password": "123456789"
}

### Request 4
GET http://127.0.0.1:8000/api/auth/validate_token/
Content-Type: application/json
Accept: application/json
Authorization: Bearer bab4fb664f9b483966828c5d7fde67dd2beb9060

### Request 1 
GET http://127.0.0.1:8000/api/articles

### Request 2
POST http://127.0.0.1:8000/api/articles/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTkwOTYyLCJpYXQiOjE3MzU1OTA2NjIsImp0aSI6ImZiYTg1NWZkNWIxNzQyOTVhOWM4YmIwZGE2MjVjM2RjIiwidXNlcl9pZCI6MjF9.ASV2xVbck27qtzY8gHSylFO5Bn7cgQvxNNnnNEhQBnw

{
    "title": "Test Article",
    "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer",
    "tags": "test,article"
}

### Request 5
GET http://127.0.0.1:8000/api/articles/?is_published=true&search=Reason&tags=message

